# Generated by Django 3.0.6 on 2020-05-15 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='specialty',
            name='picture',
        ),
    ]
